### ISSUE TITLE
QUIC performance protocol support

### ISSUE THREAD

**Issue by bt90** [ngtcp2/ngtcp2#1045]
It would be nice to have support for https://datatracker.ietf.org/doc/html/draft-banks-quic-performance-00

This might help with performance related tests and troubleshooting like https://github.com/ngtcp2/ngtcp2/issues/1029

Implementations of other QUIC libraries:

* MsQuic: https://github.com/microsoft/msquic/tree/main/src/perf#secured-network-performance-testing
* quic-go: https://github.com/quic-go/perf

**Comment by tatsuhiro-t** [comment]
We once had those implementations but they have been removed because of maintenance overhead and not used much.
Perf issues can be verified by h3 client or h09 client, it does not require special purpose client in my opinion.
Most likely perf issue exists because someone adds extra calls of APIs or socket calls in a hope that they fix their issue, but not.
