### ISSUE TITLE
how does ngtcp2 implement 0rtt ?

### ISSUE THREAD

**Issue by NKTelnet** [ngtcp2/ngtcp2#111]
A client connects to ngtcp2 server and saves the session file, then it disconnects to the server. Now the related session will be removed from the ngtcp2 server. After that, the client uses the saved session file to connect to the ngtcp2 server and send 0rrt data to the server, the 0rtt data will be rejected by the ngtcp2 server because server can not find the related previous session by ssl_get_prev_session(). 

Is this reasonable for quic 0rtt ?

**Comment by tatsuhiro-t** [comment]
You don't need any state in server side because session state is embedded in session ticket.
I think this is more like how you use TLS stack rather than ngtcp2.  Assuming that you are using OpenSSL, by default, OpenSSL TLSv1.3 implementation requires that TLS session must be in memory session cache to prevent replay attack.  Obviously this does not work if you have multiple servers behind the load balancer, and it requires more state in server side.  You have to use some options to disable this default behaviour.
There is more.  If you want to make session ticket work with server restart or multiple servers, you have to implement callback function to provide a secret key to encrypt session ticket.  You have to rotate the key frequently in practice.  Again, these details are for OpenSSL, not for ngtcp2 because ngtcp2 does not depend on any particular TLS backend.
