### ISSUE TITLE
PMTUD finished callback

### ISSUE THREAD

**Issue by sshock** [ngtcp2/ngtcp2#1179]
Hi, could we have a callback for when PMTUD has completed?

I know it's usually quite fast, but rather than guess when it might be done, e.g., by calling `ngtcp2_conn_get_path_max_tx_udp_payload_size()` repeatedly until it seems to not be changing anymore, it would be very useful for me to just be notified when ngtcp2 has finished.

Maybe just invoke this callback from the `ngtcp2_conn_stop_pmtud` method?

Thanks!

**Comment by tatsuhiro-t** [comment]
What is the real use case of knowing pmtud completion?  It is basically an optimization to expand UDP payload size, and in general application do not need to know its completion.

**Comment by sshock** [comment]
> What is the real use case of knowing pmtud completion?

I'll be leveraging the PMTUD result to help set the MTU on a separate, non-QUIC, UDP tunnel (between the same endpoints, but used for a different purpose).

**Comment by tatsuhiro-t** [comment]
Thank you for sharing the use case.  If this is a feature request, it is very low priority and I have no plan to add that at the moment because the use case is rather your specific one and not generally useful for ngtcp2 library users.  Adding a callback is huge deal even if the implementation is simple because once it is added I have to maintain it during whole v1 period.

**Comment by sshock** [comment]
Ok, I appreciate the consideration.
