### ISSUE TITLE
Change ngtcp2_crypto_level ordering

### ISSUE THREAD

**Issue by DaanDeMeyer** [ngtcp2/ngtcp2#127]
The BoringSSL encryption level enum order is: initial, early_data, handshake, application.

Would it be feasible for ngtcp2 to adopt the same order? It saves users from requiring custom conversion functions between the two enums.

**Comment by tatsuhiro-t** [comment]
I think putting early_data at the end has good use case.
Because we don't send any CRYPTO data in 0RTT packet, we just keep CRYPTO data for the other 3 encryption levels.  Current order of enum allows us to store those objects in 3 length array and can access it through enum value without wasting space.
See https://github.com/ngtcp2/ngtcp2/blob/79cde04cb313e30f148c65382fd8188c0c3b6385/examples/client.h#L261
