### ISSUE TITLE
ngtcp2_conn.c:5866: conn_prepare_key_update: Assertion `conn->callbacks.update_key' failed.

### ISSUE THREAD

**Issue by bagder** [ngtcp2/ngtcp2#199]
I build curl with ngtcp2 and nghttp3 and run into this issue:

~~~
$ ./src/curl --http3 -v https://nghttp2.org:4433/
* STATE: INIT => CONNECT handle 0x55cee627d9a8; line 1491 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x55cee627d9a8; line 1532 (connection #0)
*   Trying 139.162.123.134:4433...
* Connect socket 3 over QUIC to 139.162.123.134:4433
* STATE: WAITRESOLVE => WAITCONNECT handle 0x55cee627d9a8; line 1611 (connection #0)
* Received 18 bytes data on stream 3
* Received 1 bytes data on stream 11
* Received 1 bytes data on stream 7
* QUIC handshake is completed
curl: ngtcp2_conn.c:5866: conn_prepare_key_update: Assertion `conn->callbacks.update_key' failed.
Aborted
~~~

I'm running Debian Unstable Linux, this curl from git master (curl-7_67_0-22-gb3eb7d172), ngtcp2 from git master (af48e33a8e2bb) and nghttp3 from master (5cd9945a0eef23f39f).

**Comment by tatsuhiro-t** [comment]
I changed the timing of next traffic key generation and it requires the application to provide ngtcp2_update_key callback even if key update has not been initiated.

In this callback, application has to generate new traffic key.  In order to generate new keys, `ngtcp2_crypto_update_key` is handy.

**Comment by bagder** [comment]
Thanks!

Any chance you can give us a hand with that? I've looked at how do you it in the `client.cc` code but honestly, I don't understand it...

**Comment by tatsuhiro-t** [comment]
The new secret is derived from the previous secret.  I think curl has to store the first secret somewhere in struct.  https://github.com/curl/curl/blob/7627a2dd9d4b7417672fdec3dc6e7f8d3de379de/lib/vquic/ngtcp2.c#L163 provide rx_secret and tx_secret.  If level == NGTCP2_CRYPTO_LEVEL_APP, store them somewhere.  I plan to store these secrets in ngtcp2_conn in order to make this process easier.  For now, application has to do extra step.

In ngtcp2_crypto_update_key, the remembered rx_secret and tx_secret are passed to ngtcp2_crypto_update_key as current_rx_secret and current_tx_secret.  The function writes new secret and traffic keys and IVs in the provided buffers.
The length of secret is same as the current one.  Once new secret is obtained, application should keep it for the next generation of secrets.  It can discard current secrets.

**Comment by bagder** [comment]
The `quic_set_encryption_secrets` is a callback from OpenSSL, surely the level check should be `ossl_level == ssl_encryption_application` there?

**Comment by bagder** [comment]
Closing, fixing this issue on the curl side of things.
