### ISSUE TITLE
Missing support for keep alive?

### ISSUE THREAD

**Issue by jpboivin** [ngtcp2/ngtcp2#220]
Hello,

We've seen in some of our integration tests a behavior that suggest that ngtcp2 lacks support for a keep alive. QUIC says in [section 19.2](https://tools.ietf.org/id/draft-ietf-quic-transport-27.html#name-ping-frame) of the draft that PING frames should be used to keep a connection alive. ngtcp2 doesn't seem to expose any way for an application to write PING frames, nor any automatic keep alive with options. I've looked in the code, and PING frames doesn't seem to be sent after the handshake.

Is it a known issue, and if so, is it planned to add support for keep alive in ngtcp2?

**Comment by tatsuhiro-t** [comment]
At the moment, no functionality is available to send PING by application.
I probably add it later, but it is now in lower priority because it is considered optional (perhaps, YMMV).  If application protocol needs this functionality, it should provide its own mechanism to keep connection alive (e.g., WebSocket ping).

**Comment by tatsuhiro-t** [comment]
[ngtcp2_conn_set_keep_alive_timeout](https://nghttp2.org/ngtcp2/ngtcp2_conn_set_keep_alive_timeout.html) has been added to send PING frame in a packet when connection is idle in a configured time period.
