### ISSUE TITLE
PSK mode?

### ISSUE THREAD

**Issue by ericcurtin** [ngtcp2/ngtcp2#271]
Similar to the last issue posted, some industries have a tendency to use PSK encryption over certificates. Would this be possible to add to ngtcp2?

**Comment by sshock** [comment]
I'm also wondering about the possibility of adding support for (external) PSK authentication.

I don't think picotls supports it yet, but I believe most of the other TLS backends do, so maybe it wouldn't be too difficult to add?

**Comment by tatsuhiro-t** [comment]
FYI, nghttpx proxy supports PSK and it works with QUIC connection as well.
https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-psk-secrets

The documentation was written when TLSv1.2 was the latest version.  With TLSv1.3, cipher suite restriction is gone.

**Comment by tatsuhiro-t** [comment]
It looks like SSL_CTX_set_psk_use_session_callback and SSL_CTX_set_psk_find_session_callback have been introduced for TLSv1.3.
The known issue I found so far is 0RTT.  It seems it is impossible to do 0RTT over QUIC because OpenSSL does not export necessary information to an application, in particular, ssl->psksession.

**Comment by sshock** [comment]
Thanks for all the helpful info!  I'm happy to hear it's not an ngtcp2 omission, but rather just depends on what the underlying TLS backend supports.

Soon I'm hoping to test ngtcp2 with picotls patched with [this PR](https://github.com/h2o/picotls/pull/321).
