### ISSUE TITLE
For the ack behavior by acked_crypto_offset in ngtcp2_conn_callbacks 

### ISSUE THREAD

**Issue by optimistyzy** [ngtcp2/ngtcp2#275]
Hi, 
In version 841d82f16063066b01589a3fe06768ebf871b1ed, when a side sends the data with stream and receives the data, it will always trigger the ack info, which means that the user defined call back function pointed by acked_crypto_offset in ngtcp2_conn_callbacks will be called.  But today when I checkout the master branch today(d7770c3ca6b6c40fbba84851f6bc65694e45742e). I found that when the side sends the data and receives the data, the corresponding call back function will not be called.  So I am curious what's the change for the strategy.

Thanks.

**Comment by optimistyzy** [comment]
@tatsuhiro-t I did some analysis, it is cause by this checkin (a38cf243f8cceaf560db7aefb63e65cdf34edd1a). Before this patch, my program with NGTCP2 is OK for my testing working rounds. But after this patch, it does not work.

**Comment by JunqiWang** [comment]
I'm experiencing similar problem and my bisect points to the same commit as @optimistyzy stated above (a38cf24). The symptom is `stream_closed` callback is not invoked though client received stream frame with `fin=1`

**Comment by tatsuhiro-t** [comment]
Let me check.

**Comment by JunqiWang** [comment]
Yeah, the symptom isn't exactly the same. The thing in common is some callback is supposed to be invoked but with this commit they are not. I'm also investigating on my side and will share once I find something new.

**Comment by JunqiWang** [comment]
FWIW, after some more digging I found our test relied on certain ACK behavior that's changed with this commit. Previously, since server will send MAX_DATA right after handshake_complete and server will append an ACK together with the MAX_DATA frame regardless of what ACK_THRESHOLD is. With this commit, server no longer sends MAX_DATA immediately after handshake_complete (which I believe is the desired the behavior).
I don't have problem with this commit anymore and we'll fix on our side. Thanks @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
It is OK not to send MAX_DATA if an endpoint thinks that there is enough flow control credit left.  At the same time, there is no requirement of certain ordering of frames in QUIC, so implementation should not rely on them.
Closing this issue as this is not an ngtcp2 issue.
