### ISSUE TITLE
How to detect ngtcp2_conn_shutdown_stream_read() on the remote endpoint?

### ISSUE THREAD

**Issue by rhoxn** [ngtcp2/ngtcp2#324]
When a client calls ngtcp2_conn_shutdown_stream_read(), there is no notification on the server side. How should the server detect it?

Furthermore, if the client sends Fin after calling ngtcp2_conn_shutdown_stream_read(), no callback is called on the server side as well. (Fin will not be received either).
Since both sending and receiving are terminated in this case, it is expected that at least ngtcp2_stream_close will be called back.

However, if the client calls ngtcp2_conn_shutdown_stream_read() after sending Fin, the callbacks will be called in the following order.

1. Server receives Fin in ngtcp2_recv_stream_data callback.
2. ngtcp2_stream_stop_sending is called back by the client.
3. ngtcp2_stream_reset is called back by the client.
4. ngtcp2_stream_close is called back by client and server.

It is my understanding that the call to ngtcp2_conn_shutdown_stream_read() triggers the sending of a STOP_SENDING frame. The endpoint that receives the STOP_SENDING frame should send back a STREAM_RESET frame.
However, both ngtcp2_stream_stop_sending and ngtcp2_stream_reset were called back on the client side.
I thought that the ngtcp2_stream_stop_sending callback would be called when a STOP_SENDING frame is received, but that doesn't seem to be the case.
Is this the intended behavior?

**Comment by tatsuhiro-t** [comment]
These callbacks are implemented expectedly.  Calling ngtcp2_stream_stop_sending when a local endpoint sends STOP_SENDING is required for HTTP/3 to cancel QPACK data.
At the moment, there is no way to immediately know that STOP_SENDING is received.
However, application will get NGTCP2_ERR_STREAM_SHUT_WR when it tries to send application data (ngtcp2_conn_writev_stream) if it already received STOP_SENDING.
Application which is desperately trying sending data will promptly know that sending side stream is closed by this.
Application which has no data to send will not know this until stream is closed, but since it has no data to send, knowing STOP_SENDING is received is not that important.

> Furthermore, if the client sends Fin after calling ngtcp2_conn_shutdown_stream_read(), no callback is called on the server side as well. (Fin will not be received either).
Since both sending and receiving are terminated in this case, it is expected that at least ngtcp2_stream_close will be called back.

Will check this out.  Sounds like a bug.

**Comment by rhoxn** [comment]
I'm sorry. It was a problem with my test code that the callback was not performed. After fixing it, the callback was done correctly.

Indeed, as you said, in most cases it is enough to detect the shutdown when sending.
One concern I have is that the timing when the remote endpoint application can detect the app_error_code specified in ngtcp2_conn_shutdown_stream_read() is delayed until the ngtcp2_stream_close callback stage.

However, I am wondering what the general use of shutdown in the receive direction is.
Just out of curiosity, do you know what use cases the Quic specification for shutting down only the receive direction was designed for?

**Comment by tatsuhiro-t** [comment]
The prominent use case of STOP_SENDING is that HTTP/3 server asks client to stop sending request body after the server generated response completely without request body, for example, because server does not support POST/PUT or detected some defects in client request header fields.

**Comment by rhoxn** [comment]
I see, it's used to send a response while avoiding extra POSTs.
I'll reopen this issue if I find the need to detect STOP_SENDING immediately.
Thanks.
