### ISSUE TITLE
Is it feasible to use session tickets to resume a session instead of the whole TLS session?

### ISSUE THREAD

**Issue by msoxzw** [ngtcp2/ngtcp2#466]
[TLS 1.3 only uses session tickets to resume a session](https://datatracker.ietf.org/doc/html/rfc8446#section-4.6.1). Unfortunately, the whole TLS session is used for session resumption in ngtcp2. Because the entire TLS session is much larger than a session ticket, it may unnecessarily increase external session cache pressure.

**Comment by tatsuhiro-t** [comment]
Is this issue expected to be resolved by #465?

**Comment by msoxzw** [comment]
No, this is a separate issue. In addition, it seems that [Neqo could use session tickets for session resumption](https://searchfox.org/mozilla-central/rev/97c13320e56884daf14016048e9d2182c880f8a9/third_party/rust/neqo-transport/src/connection/mod.rs#1853-1863).

**Comment by tatsuhiro-t** [comment]
ngtcp2 as a library does not know how resumption ticket is constructed.  It does not even know they are exchanged.
Those CRYPTO messages are completely opaque to ngtcp2 library and everything passed down to or from TLS stack.
Are you referring to the particular implementations of client/server under examples directory?
If TLS library has a capability to export just only received TLS session ticket, and then import it back, then they can do what you described.

**Comment by msoxzw** [comment]
Thanks for your insightful comment. Whether or not TLS session tickets can be retrieved, indeed depends on the TLS library.
The [SSL_SetResumptionTokenCallback](https://searchfox.org/mozilla-central/rev/a6d25de0c706dbc072407ed5d339aaed1cab43b7/security/nss/lib/ssl/sslexp.h#466-480) in nss, and the [SSL_process_tls13_new_session_ticket](https://github.com/google/boringssl/blob/efd09b7e370e6975f795cdbc54ff6e0941ebf274/include/openssl/ssl.h#L2270-L2282) in BoringSSL, have session tickets accessible. Besides, given [SSL_process_tls13_new_session_ticket](https://github.com/google/boringssl/blob/efd09b7e370e6975f795cdbc54ff6e0941ebf274/include/openssl/ssl.h#L2270-L2282) implementation, a resumable TLS session that consists almost entirely of the session ticket can be constructed from an intact TLS session.
Furthermore, would you mind sharing your position on TLS libraries, particularly paired with ngtcp2?

**Comment by tatsuhiro-t** [comment]
ngtcp2 library has no opinion about how session is resumed.  I think you are referring to the particular implementations under examples directory which store the entire session in disk which is too large.  They are just examples.
If you are asking me the preference of TLS libraries, I do not have the particular preference over the other.
For the ease of availability, gnutls would be a good choice because they are available as a package in OS distributions.
But in reality, an application has already chosen TLS library for use.  If it wants OpenSSL like TLS library, it probably does not use gnutls.
