### ISSUE TITLE
Configurable padding of QUIC packets

### ISSUE THREAD

**Issue by Payne-X6** [ngtcp2/ngtcp2#626]
While reading through RFC-9250 I came across the [5.4. Padding](https://datatracker.ietf.org/doc/html/rfc9250#section-5.4) section. Is there an option in `ngtcp2` to set the desired padding? If not, is it possible to add this feature?

**Comment by tatsuhiro-t** [comment]
There is no function to specify the desired padding.  This kind of API is somewhat not easy to use because application needs to know whether specific frames are included in a packet that could lead to more complicated design decisions and code lines.
For now, it would be better to use DNS extension to add padding if needed.
