### ISSUE TITLE
Want to use ngtcp2 for project

### ISSUE THREAD

**Issue by Vasu-p** [ngtcp2/ngtcp2#63]
Hi,
I want to use this library for a project in which I am trying to port a protocol called MQTT to run over QUIC. I saw the example server and client but was not able to understand how exactly can I carry a simple task of establishing a connection and send some data over streams and close connection. Apart from that how may I specify if connection should be 1RTT or 0RRT. If you can point me to some direction it would be really appreciated. Thanks

**Comment by tatsuhiro-t** [comment]
Basically application has to implement callback functions, and write/receive stream data, but at the moment, we largely lack documentation about it.
The design decision which makes libngtcp2 independent of TLS stack causes the use of the library a bit tedious.  It is not so difficult I think.  The hard part is doing TLS handshake.  After that is passed, it would be easier; just send and receive stream ordered data.
I'll add more documentation, but before that, I'll write summary here how to use the library.

In order to use 0-RTT, you have to have a session ticket.  As long as you have it, and you can send 0-RTT.  Server might reject it though.

**Comment by Vasu-p** [comment]
Great. Thanks. That would be nice.

**Comment by tatsuhiro-t** [comment]
Will do.
At the moment, I'm doing refactoring internals as well as APIs.  Once it is settled, I'll write some documentation.

**Comment by addogra** [comment]
can you give us the pointers for the documentation of the api's so that we can start using ngtcp2 in our project ?

**Comment by tatsuhiro-t** [comment]
The online documentation is now available https://nghttp2.org/ngtcp2/
