### ISSUE TITLE
client does not expect a packet from unknown path

### ISSUE THREAD

**Issue by yzcwf** [ngtcp2/ngtcp2#691]
In the function `ngtcp2_conn_read_pkt_versioned`, a path validation is performed on the data packets received from the client, and packets received from an unknown path are discarded. The validation for an unknown path simultaneously checks both the local address and the remote address. Should only the remote address be checked, considering that `ngtcp2_conn_set_local_addr` can change the local address, and this function is used  during NAT rebinding tests or connection migration?

**Comment by tatsuhiro-t** [comment]
I think the current implementation is fine.  In real scenario, NAT rebinding happens without client noticing it.  For client, its local address does not change after NAT rebinding.  ngtcp2_conn_set_local_addr exists just for test purpose only in order to simulate NAT rebinding.  I will add a text to the function so that readers know that it is meant to be testing purpose only.
