### ISSUE TITLE
Minimum quantum size

### ISSUE THREAD

**Issue by amirlivneh** [ngtcp2/ngtcp2#736]
What's the rationale for using a minimum quantum size of 10 for BBR and BBRv2? E.g.

https://github.com/ngtcp2/ngtcp2/blob/0a885744e0552ff7b00b5060538e8d0a3de75cef/lib/ngtcp2_bbr.c#L390

Both [the BBR draft](https://www.ietf.org/archive/id/draft-cardwell-iccrg-bbr-congestion-control-02.html#section-4.6.3) and [mvfst](https://github.com/facebookincubator/mvfst/blob/e56d4bd7f655637494826d4ace26d96f9d84f39c/quic/QuicConstants.h#L367), for example, specify a lower minimum value.

I also heard that the Linux kernel and Quiche use a minimum quantum of 2 above 1.2 Mbps, although I don't have links to the code.

There is a concern in our team that a quantum size of 10 may be too high for many of our user's uplinks, resulting in bursty pacing.

**Comment by tatsuhiro-t** [comment]
This was added because bbr otherwise was considerably slower than cubic on my local test environment.
Since then we fixed number of bugs and performed several perf related tunings.  Will check this is still relevant.
10 packets burst was once suggested in pre RFC9002 draft when pacing is not used and it is basically CWND=10, so that is not huge burst IMO.

**Comment by tatsuhiro-t** [comment]
Looks like there are not much difference when following the draft now.  #737 changes the code to follow the draft.
