### ISSUE TITLE
Possible regression between 0.13.1 and 0.14.1

### ISSUE THREAD

**Issue by salzmdan** [ngtcp2/ngtcp2#742]
Hello!

We successfully use ngtcp2 for DNS over QUIC implementation. However, since upgrade from 0.13.1 to 0.14.1 we have been observing unreliable transfer of more message (some are missing). Commit https://github.com/ngtcp2/ngtcp2/commit/b7499d9321b9bfe6d7d69fe31e5c4d145e848d66 caused the "regression". Please do you think it's a bug in the library or possibly incorrect usage of the library?

Thank you for any help and this library!

**Comment by tatsuhiro-t** [comment]
The commit improves the peak transfer rate with reno and cubic, which is previously limited because congestion window is not properly extended when processing delay gets large.
These types of congestion controller are loss based, so it is natural to see some losses when it sends too fast or too much, and then decreases the transfer rate.  Previously, it limits transfer rate well below than it should be, so it sees less loss signals.
There are some toggles in OS that increase UDP receive buffer size to receive more UDP traffic.  Also some old NIC cannot keep up with higher transfer rate (e.g., old wifi), it is advised to retry sendmsg() when it returns EAGAIN or EWOULDBLOCK.
If you think the loss is not nice, bbr or bbr2 congestion controllers might help.

**Comment by salzmdan** [comment]
Thanks for the hints! Changing CC algorithm doesn't help. Only increasing `net.core.rmem_default`. Still trying to understand how to properly mitigate the issue...

BTW shouldn't be `min_rtt` replaced with `smoothed_rtt` in
https://github.com/ngtcp2/ngtcp2/blob/b7499d9321b9bfe6d7d69fe31e5c4d145e848d66/lib/ngtcp2_cc.c#L181
https://github.com/ngtcp2/ngtcp2/blob/b7499d9321b9bfe6d7d69fe31e5c4d145e848d66/lib/ngtcp2_cc.c#L190
and similarly in the `ngtcp2_cc_cubic_cc_on_ack_recv()`?

**Comment by tatsuhiro-t** [comment]
Needs min_rtt in L181 so that we only set target_cwnd when rtt sample is retrieved.
L190 should be smooth_rtt, thanks.

So the offending code is only executed on reno or cubic cc.  Using bbr or bbr2 does not change anything, then it means that the cause is elsewhere.

**Comment by tatsuhiro-t** [comment]
#745 fixes the 2nd issue.
